#!/bin/bash
#
# Pandoc preprocessor (reads YAML front matter to extract metadata)
#
# usage:
#
#    pandocwrapper --type:<ext> <in_file>
#
# What it does:
#
#  1. for pdf/latex extracts documentclass (if exists)
#  2. if documentclass exists, passes a metadata variable named as the
#     documentclass value (e.g. for ieeetrans, the variable is named
#     'ieeetrans') with a value of 'true'.
#  3. for pdf/latex, adds a workaround to use hanged indentation for
#     references (see [1])
#  4. If PANDOC_EXTRA_ARGS variable is defined, it appends it to the arguments 
#     passed to pandoc
#
# To-do:
#   - have a variable 'layout' (which takes values like poster, slides, paper,
#     post, extended-abstract, index)
#   - layout is end-format-agnostic. Other variables (such as documentclass)
#     specialize the output.
#
# [1]: https://groups.google.com/forum/#!topic/pandoc-discuss/SUZ08-Kc6Og)

# check arguments
if [ "$#" -ne 1 ] && [ "$#" -ne 2 ]; then
  echo "Illegal number of parameters"
  echo "Usage:"
  echo "  pandocwrapper [--type=(pdf|htm|tex|beam|odt)] file.md"
  exit 1
fi

# write
write_log=1

# get the "--type=" argument value
for arg in "$@"
do
  if [[ $arg = "--type="* ]] ; then
    output_type=${arg#--type:*}
  fi
done

# select pdf if not defined
if [ -n $output_type ] ; then
  output_type="pdf"
fi

# get input filename path (without extension)
input_file=$arg
dir_name=$(dirname $input_file)
base_name=$(basename $input_file)
base_without_extension=${base_name%.*}
input_prefix=$dir_name/$base_without_extension

# check if file exists
if [ ! -f $input_file ] ; then
  echo "ERROR: File $input_file doesn't exist"
  exit 1
fi

# common args
common_all=\
" --standalone "\
" --latex-engine=xelatex"\
" --self-contained"\
" --csl=$HOME/.citations/ieee.csl"\
" --bibliography=$HOME/.zotero.bib"\

# small workaround for re-routing pdf -> beamer
if [ $output_type = "pdf" ] ; then
  echo "rerouting from pdf to beam" >> /tmp/pandoc_args.log
  is_beamer=`cat $input_file | grep "layout: extended" | sed -e's/extended//'`

  if [ $is_beamer ] ; then
    output_type="beam"
  fi
fi

# define the args for each file type
if [ $output_type = "pdf" ] ; then
  args_for_type="-o "$input_prefix".pdf  --reference-links"
elif [ $output_type = "htm" ] ; then
  args_for_type="-o "$input_prefix".html -t html5 --ascii --reference-links"
elif [ $output_type = "tex" ] ; then
  args_for_type="-o "$input_prefix".tex"
elif [ $output_type = "txt" ] ; then
  args_for_type="-o "$input_prefix".txt"
elif [ $output_type = "beam" ] ; then
  args_for_type="-o "$input_prefix".pdf  -t beamer --template=extended"
elif [ $output_type = "dz" ] ; then
  args_for_type="-o "$input_prefix".html -t dzslides"
elif [ $output_type = "s5" ] ; then
  args_for_type="-o "$input_prefix".html -t s5"
elif [ $output_type = "rv" ] ; then
  args_for_type="-o "$input_prefix".html -t revealjs"
elif [ $output_type = "odt" ] ; then
  args_for_type="-o "$input_prefix".odt"
elif [ $output_type = "docx" ] ; then
  args_for_type="-o "$input_prefix".docx"
else
  echo "UNKWNOWN type $output_type"
  exit 1
fi

# for pdf/latex extract documentclass (if exists)
if [ $output_type = "pdf" ] || [ $output_type = "tex" ] ; then
  documentclass=`cat $input_file | grep documentclass: | sed -e's/documentclass: //'`
  if [ $documentclass ] ; then
    args_for_type="$args_for_type --metadata=$documentclass:'yes'"
  fi

  hangedbiblio=`cat $input_file | grep hanged-biblio: | sed -e's/hanged-biblio: //'`
  if [ $hangedbiblio ] ; then
    cat $input_file > /tmp/inputfile.pd
    echo "" >> /tmp/inputfile.pd
    echo "\\noindent" >> /tmp/inputfile.pd
    echo "\\vspace{-2em}" >> /tmp/inputfile.pd
    echo "\\setlength{\\parindent}{-0.3in}" >> /tmp/inputfile.pd
    echo "\\setlength{\\leftskip}{0.3in}" >> /tmp/inputfile.pd
    echo "\\setlength{\\parskip}{8pt}" >> /tmp/inputfile.pd

    input_file="/tmp/inputfile.pd"
  fi

fi

#pandoc_cmd="docker run -v `pwd`:/data"
pandoc_cmd="pandoc"

cmd="$pandoc_cmd $common_all $args_for_type $PANDOC_EXTRA_ARGS $input_file"

echo "$cmd" > /tmp/pandoc_args.log

if [ $write_log -eq 1 ] ; then
  $cmd 2> /tmp/pandoc.log
else
  $cmd 2> /dev/null
fi

ret_code=$?
if [ $ret_code != 0 ]; then
  echo "Error when executing pandoc, check the log"
  case "$OSTYPE" in
    darwin*)
      afplay -v 50 /System/Library/Sounds/Basso.aiff
    ;;
  esac
  exit $ret_code
fi

case "$OSTYPE" in
  darwin*)
    afplay -v 50 /System/Library/Sounds/Pop.aiff
  ;;
esac
